[package]
name = "goku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.14"
tokio = {version="1.25.0", features = ["full"] }
futures = "0.3.26"
rand = "0.8.5"
num_cpus = "1.15.0"
