[package]
name = "goku-bench"
version = "1.0.1"
edition = "2021"
authors = ["Joaquin Caro <me@joaquin-caro.es>"]
description = "Goku is an HTTP load testing application written in Rust "
repository = "https://github.com/jcaromiq/goku"
keywords = ["performance", "http", "benchmark", "load-testing", "performance-testing"]
license = "MIT"

[[bin]]
name = "goku"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
reqwest = "0.11.14"
tokio = { version = "1.26.0", features = ["full"] }
futures = "0.3.27"
clap = { version = "4.1.9", features = ["derive"] }
hdrhistogram = "7.5.2"
colored = "2.0.0"
strum = { version = "0.24.1", features = ["derive"] }
anyhow = "1.0.69"
ctrlc = "3.2.5"
serde_yaml = "0.9.19"
serde = { version = "1.0.156", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.3.0"


[profile.release]
strip = true
opt-level = 'z'
lto = true
codegen-unit = 1
panic = 'abort'
